site_name: FOSS

theme:
  name: material

extra_css:
  - stylesheets/custom.css

nav:
  - Home: index.md
  - Moodle:
    - Introduction: moodle/moodleReadme.md
    - Site Admin:
      - Moodle Admin Guide: moodle/admin-guide/site-admin.md
      - Practice Moodle in VirtualBox: moodle/admin-guide/Practice-Moodle-VirtualBox&UTM.md
      - Moodle language pack: moodle/admin-guide/mdl-language-pack.md
      - Customize Moodle Themes: moodle/admin-guide/Customize_Moodle_themes.md
      - Configuring Email Outgoing: moodle/admin-guide/Configuring-Email-Outgoing.md
      - External Authentication: moodle/admin-guide/Learn-SSO.md
      - Plugin Installation: 
        - Interactive content: moodle/admin-guide/Install-H5P-plugin.md
        - Virtual Programming Lab - VPL: moodle/admin-guide/installVPL.md
        - Board: moodle/admin-guide/install-boad.md
        - Workplace Course Certificate: moodle/admin-guide/Workplace-Certificate.md
        - Checklist: moodle/admin-guide/Checklist-pluging.md 
        - Completion Progress: moodle/admin-guide/Progress-plugin.md
        - Attendance Activity Plugin: moodle/admin-guide/attendance-plugin.md
        - Mass Enrolments: moodle/admin-guide/Mass-enrolments.md
    - Manager Faculty Co Ordinator :
      - Moodle Manager: moodle/managerfaculty/manager.md
      - Adding users: moodle/managerfaculty/Adding-users.md
      - Adding a Course Category: moodle/managerfaculty/add.md
    - Teacher:
      - Assignments: moodle/TeachersGuide/Assignment-activity.md
      - Quizzes & Questionnaires: moodle/TeachersGuide/Quizzes&Questionnaires.md
      - Moodle-Virtual-Class-Room-(Webinar): moodle/TeachersGuide/Moodle-Virtual-Class-Room-(Webinar).md
      - Interactive Content: moodle/TeachersGuide/Interactive-content.md 
      - Creating and Managing Forum: moodle/TeachersGuide/Forum-activity.md
      - Enable Safe Exam Browser: moodle/TeachersGuide/Enable-Safe-Exam-Browser.md
      - SCORM: moodle/TeachersGuide/SCORM.md
      - Feedback: moodle/TeachersGuide/Feedback.md
      - Surveys: moodle/TeachersGuide/Survey-activity.md
      - Attendance/Reports: moodle/TeachersGuide/Attendance-activity.md
      - Grading: moodle/TeachersGuide/Grading.md
      - Virtual Programming Lab - VPL: moodle/TeachersGuide/VirtualProgrammingLab-VPL.md
      - Board - Plugin: moodle/TeachersGuide/mdl-board.md
      - Workplace Course Certificate: moodle/TeachersGuide/course-certificate.md
      - Checklist - Plugin: moodle/TeachersGuide/Checklist.md
      - Completion Progress - plugin: moodle/TeachersGuide/completion-progress.md
      - Bulk Enrolments plugin: moodle/TeachersGuide/bulk_enrolments.md
    - Student Guide: 
      - Getting Start: moodle/StudentGuide/getting-started.md
      - Navigating Courses,Submit the Assignment,Quiz Submission: moodle/StudentGuide/Courses-Assignment-Quiz-Submission.md
      - Submit the Forum: moodle/StudentGuide/Submit-Forum.md
      - Feedback activity,Survey Submission: moodle/StudentGuide/feedback-Survey-Submission.md
      - Join in VCR Class Room: moodle/StudentGuide/Join-VCR.md
      - Safe Exam Browser: moodle/StudentGuide/Safe-Exam-Browser.md
  - DSpace: 
    - Introduction: dspace/README.md
    - Site Admin(Create Community,Sub-Community,Collectio): dspace/siteadmin.md
    - Community and Collection Admin Roles: dspace/Community&Collection-Admin.md
    - Add Users and Assign Roles: dspace/AddUserstoDSpace.md
    - Submitter: dspace/Submitter.md
    - Reviewer & Editors: dspace/reviewer_editor_finalEditor.md
    - ORCID Sandbox + DSpace integration: dspace/Integrate-ORCID-Sandbox.md
  - WordPress:
    - Build Your Own Website: wordpress/build-website.md
    - Practice WordPress: wordpress/Practice-Wordpress.md
    - Site-Backup & Restore: wordpress/Site-Backup&Restore.md
  - Indico:
    - Introduction: indico/README.md
    - Conference Planing : indico/GeneralConferencePlanningProcess.md
    - Indico Setup:
      - Accounts & Profiles: indico/indico-setup/CreateAccountAndUpdateProfile.md
      - Admin Tasks: indico/indico-setup/Admin.md
      - Event Creation: indico/indico-setup/CreateConferenceEvent.md
      - Assign Organizers & Permissions: indico/indico-setup/AddEventManagersAndAssignPermissions.md
      - Event Configurations: indico/indico-setup/AddEventDeadlinesAndScheduleConfiguration.md
      - Registration Module: indico/indico-setup/RegistrationModule.md
      - Email Notifications: indico/indico-setup/EmailNotifications.md
      - Add Contributions: indico/indico-setup/AddContributions.md
      - Paper Submission: indico/indico-setup/UploadPresentation.md
      - Certificate: indico/indico-setup/Certificate.md
      - Room Booking: indico/indico-setup/RoomBooking.md
      - Feedback Form: indico/indico-setup/Feedback.md
  - VCR:
    - Introduction: vcr/README.md
    - Room & Session Management:
      - Sign in to vCR: vcr/Room&Session Management/signintoVCR.md
      - Create a vCR Room : vcr/Room&Session Management/Create&DeleteRoom.md
    - Instructor / Moderator Features:
      - Overview for Instructors (moderator / presenter):
        - Room Management:
          - Start / End a Room and leave a room: vcr/InstructorModerator Features/Overview for Instructors/Room Management/start&Ending-room.md
          - Invite Co-Hosts: vcr/InstructorModerator Features/Overview for Instructors/Room Management/Co-Host.md
          - Enable / Disable Waiting Room (Guest Policy): vcr/InstructorModerator Features/Overview for Instructors/Room Management/waitingRoom.md
        - Content Sharing:
          - Upload / Manage Presentation: vcr/InstructorModerator Features/Overview for Instructors/ContentSharing/uplord-ppt&sharing.md
          - Share External Videos (e.g., YouTube): vcr/InstructorModerator Features/Overview for Instructors/ContentSharing/Sharing-External-Video&whiteboard.md
        - Participant Control:
          - Lock Viewer Features (e.g., private chat, mic, webcam, screen sharing): vcr/InstructorModerator Features/Overview for Instructors/Participant Control/Webinar-mood.md
          - Visual Assessment: vcr/InstructorModerator Features/Overview for Instructors/Participant Control/visual-assessment.md
          - Shared Notes and Export Shared: vcr/sharenote.md
        - Engagement Tools:
          - Start and Manage Polls: vcr/Engagement Tools/polling.md
          - Create and Manage Breakout Rooms: vcr/Engagement Tools/breakout-room.md
          - Launch and Manage Closed Captions: vcr/Audio&Captions/closed-caption.md
          - Use Auto Captions (Speech-to-Text): vcr/Audio&Captions/auto-caption.md
        - Monitoring & Reporting:
          - View and Download Participants List and Monitor Attendance and Engagement: vcr/InstructorModerator Features/Overview for Instructors/Monitoring&Reporting/participants-list&dashboard.md
        - Other Features:
          - Fit to Page (for presentation viewing):  vcr/InstructorModerator Features/Overview for Instructors/Other Features/fittopage.md
          - Integrate with Moodle (course-linked sessions): vcr/InstructorModerator Features/Overview for Instructors/Other Features/Moodle Virtual Class Room (Webinar).md
      - Co-Host: vcr/InstructorModerator Features/Co-Host.md
      - Visual Assessment: vcr/InstructorModerator Features/visual-assessment.md
  - LTUBE:
    - End User Guide: ltube/enduserguide.md
  - OpenShot: 
    - Introduction: openshot/README.md
    - User Interface: openshot/User-interface.md
    - Starting a New Project & Importing Media: openshot/NewProject&Importing.md
    - Editing Workflow: openshot/EnhancingVideo.md
    - Exporting Video: openshot/export-video.md
  - HandBrake:
    - Introduction: handbrake/README.md
    - Installing HandBrake: handbrake/Installing-HandBrake.md
    - Converting Video: handbrake/Converting-Video.md
    - Adjusting Basic Settings: handbrake/Adjusting-Settings.md
    - Thoubleshooting: handbrake/Troubleshooting.md
  - LibreOffice:
    - User Guide : libreoffice/libre.md
  
